services:
  config-server:
    image: config-server
    container_name: config-server
    build:
      context: ../config-server
      dockerfile: ../docker-compose/config-server/Dockerfile
    expose:
      - 8888
    ports:
      - "8888:8888"
    networks:
      - services-network
    restart: on-failure
  gateway:
    image: gateway
    container_name: gateway
    build:
      context: ../gateway
      dockerfile: ../docker-compose/gateway/Dockerfile
    depends_on:
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=github
      - CONFIG_SERVER_URL=http://config-server:8888
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      - services-network
    restart: on-failure
  bonus-service:
    image: bonus-service
    container_name: bonus-service
    build:
      context: ../bonus-service
      dockerfile: ../docker-compose/bonus-service/Dockerfile
    depends_on:
      - config-server
      - postgres
    expose:
      - 8070
    ports:
      - "8070:8070"
    environment:
      - SPRING_PROFILES_ACTIVE=github
      - CONFIG_SERVER_URL=http://config-server:8888
    networks:
      - services-network
    restart: on-failure
  flight-service:
    image: flight-service
    container_name: flight-service
    build:
      context: ../flight-service
      dockerfile: ../docker-compose/flight-service/Dockerfile
    expose:
      - 8050
    ports:
      - "8050:8050"
    depends_on:
      - config-server
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=github
      - CONFIG_SERVER_URL=http://config-server:8888
    networks:
      - services-network
    restart: on-failure
  ticket-service:
    image: ticket-service
    container_name: ticket-service
    build:
      context: ../ticket-service
      dockerfile: ../docker-compose/ticket-service/Dockerfile
    depends_on:
      - config-server
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=github
      - CONFIG_SERVER_URL=http://config-server:8888
    expose:
      - 8060
    ports:
      - "8060:8060"
    networks:
      - services-network
    restart: on-failure
  user-service:
    image: user-service
    container_name: user-service
    build:
      context: ../user-service
      dockerfile: ../docker-compose/user-service/Dockerfile
    depends_on:
      - config-server
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=github
      - CONFIG_SERVER_URL=http://config-server:8888
    expose:
      - 8040
    ports:
      - "8040:8040"
    networks:
      - services-network
    restart: on-failure
  postgres:
    image: library/postgres:16
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    networks:
      - services-network
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

networks:
  services-network:
    driver: bridge

volumes:
  db-data: