name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
      - deploy2
  pull_request:
    branches:
      - master
      - deploy2
jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install the necessary packages
        run: pip3.10 install -r requirements.txt

      - name: Run unit tests for ticket service
        run: pytest -vs ticket_service/app/unit_tests/ticket.py

      - name: Run unit tests for flight service
        run: pytest -vs flight_service/app/unit_tests/flight.py

  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # TODO build and run unit tests

      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      - name: Run containers
        timeout-minutes: 5
        run: |
          docker compose up -d
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8070,8060,8050

      # TODO setup variant, service and port

      - name: Run API Tests
        timeout-minutes: 5
        run: ./scripts/test-script.sh
        env:
          VARIANT: v1
          SERVICE_NAME: bonus_service
          PORT_NUMBER: 8050

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v
